### ISSUE TITLE
make overflow scroll

### ISSUE THREAD

**Issue by Finkregh** [vonloxley/dokuwiki-sequencediagram#2]
It would be nice if overflowing content would create a scrollbar.

example: create something that is wider than your screen
```
00->01: 
01->02: 
02->03: 
03->04: 
04->05: 
05->06: 
06->07: 
07->08: 
08->09: 
09->10: 
10->11: 
11->12: 
12->13: 
13->14: 
14->15: 
15->16: 
16->17: 
17->18: 
18->19: 
19->20: 
20->21: 
21->22: 
22->23: 
23->24: 
24->25: 
25->26: 
26->27: 
27->28: 
28->29: 
29->30: 
30->31: 
31->32: 
00a->01a: 
01a->02a: 
02a->03a: 
03a->04a: 
04a->05a: 
05a->06a: 
06a->07a: 
07a->08a: 
08a->09a: 
09a->10a: 
10a->11a: 
11a->12a: 
12a->13a: 
13a->14a: 
14a->15a: 
15a->16a: 
16a->17a: 
17a->18a: 
18a->19a: 
19a->20a: 
20a->21a: 
21a->22a: 
22a->23a: 
23a->24a: 
24a->25a: 
25a->26a: 
26a->27a: 
27a->28a: 
28a->29a: 
29a->30a: 
30a->31a: 
31a->32a: 
```

**Comment by Finkregh** [comment]
thanks, and a verison bump would be lovely :+1:

**Comment by vonloxley** [comment]
Tomorrow, I need to read-up on the release-process.

**Comment by Finkregh** [comment]
btw, you do not have to change the download-URI in the dokuwiki-plugin-directory if you change the uri for the download to something like a 'release'-branch and merge master into that one when you release/tag.

"everybody" else does simply link to the master-zipball :)
