### ISSUE TITLE
Switching to newest version of  js-sequence-diagrams?

### ISSUE THREAD

**Issue by fthommen** [vonloxley/dokuwiki-sequencediagram#5]
Hello,

are there plans to switch the sequencediagram plugin to the newest version of https://bramp.github.io/js-sequence-diagrams/ which bases on Snap.svg instead of Raphael and also has nice features like handwriting type diagrams etc.?

**Comment by vonloxley** [comment]
I hacked something into the us201 branch. In needs cleaning, but should work right now.

**Comment by fthommen** [comment]
Great! $conf['sequencediagram_layout'] doesn't appear in the configuration settings but apart from that it works like a charm.  Thanks for this quick work. I just love these pseudo-hand drawn diagrams :-)
